#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# verify rover-cli could trace the tcp connect operations of the productpage
# processes. the traffic must be generated by the productpage process itself
# (gunicorn calling details/reviews), so drive it by requesting the productpage
# page through a sidecar-free curl pod, then trace the connect during the load.
set -euo pipefail

# always clean up the traffic generator, even on early failure
cleanup() { kubectl delete pod dbg-curl -n default --force --grace-period=0 >/dev/null 2>&1 || true; }
trap cleanup EXIT

NODE=$(kubectl get pod -n default -l app=productpage -o jsonpath='{.items[0].spec.nodeName}')
[ -n "$NODE" ] || { echo "no productpage pod found" >&2; exit 1; }
ROVER_POD=$(kubectl get pod -n default -l name=skywalking-rover \
  --field-selector spec.nodeName="$NODE" -o jsonpath='{.items[0].metadata.name}')
[ -n "$ROVER_POD" ] || { echo "no rover pod on node $NODE" >&2; exit 1; }

# (re)create the traffic generator
cleanup
kubectl run dbg-curl --image=curlimages/curl:8.5.0 --restart=Never -n default \
  --annotations sidecar.istio.io/inject=false \
  -- sh -c 'for i in $(seq 1 60); do curl -s productpage:9080/productpage >/dev/null 2>&1; sleep 0.4; done' >/dev/null 2>&1
kubectl wait -n default pod/dbg-curl --for=condition=Ready --timeout=60s >/dev/null 2>&1
sleep 2

# collect the trace connect output first, then transform, so a rover-cli
# failure is not masked by yq's success(pipefail also guards the pipeline).
# the yaml stream is N event documents(have pid) followed by one statistics
# document. regroup them into a single object so one verify case can assert
# both the events and the aggregated statistics.
raw=$(kubectl exec -n default "$ROVER_POD" -- \
  /rover-cli trace connect --service productpage --duration 15s --format yaml)
echo "$raw" | yq ea '[.] | {
  "events": map(select(has("pid"))),
  "statistics": (map(select(has("statistics"))) | .[0].statistics)
}' -
